export const sapScenarios = [
  {
    id:'sap-po-release', category:'SAP MM', title:'Purchase Order not released / approval stuck', icon:'AppWindow', priority:'P3', severity:'Medium',
    symptoms:['purchase order','PO not released','approval stuck','release strategy'],
    hypotheses:[['Release strategy not triggered',35],['Approver/workflow issue',30],['Document value or classification mismatch',20],['Authorization issue',15]],
    steps:[
      {q:'Does the PO show a release or approval requirement?', help:'Confirms that the document is actually subject to approval.', yes:{next:1,boost:{'Approver/workflow issue':10}}, no:{result:'Release strategy not triggered',cause:'The PO does not meet the configured release conditions or classification values.',confidence:90,actions:['Review PO document type and value','Check release strategy/classification conditions','Compare with a similar PO that triggers approval','Escalate configuration changes to the SAP MM functional team'],escalate:true}},
      {q:'Is the expected approver able to see the PO in their approval worklist?', help:'Separates workflow routing from document configuration.', yes:{next:2}, no:{result:'Approval workflow routing issue',cause:'Approver assignment, workflow agent determination, inbox routing, or substitution is incorrect.',confidence:88,actions:['Verify approver determination','Check workflow inbox and substitution','Review workflow log if authorized','Escalate unresolved workflow configuration to SAP support'],escalate:true}},
      {q:'Does the approver receive an authorization error when releasing the PO?', help:'Checks whether the workflow reached the right person but authorization blocks the action.', yes:{result:'PO release authorization issue',cause:'The approver is missing the required SAP authorization for the release code or purchasing scope.',confidence:94,actions:['Capture the authorization error','Run the approved authorization trace/process','Request the required least-privilege role through the normal access process','Retest release after access is corrected'],escalate:true}, no:{result:'PO approval processing issue',cause:'The release step is available but has not completed due to workflow state, document changes, or pending approver action.',confidence:77,actions:['Check current release status','Review recent PO changes that may have reset approval','Confirm approver action/status','Review workflow log for the pending step'],escalate:false}}
    ]
  },
  {
    id:'sap-pr-source', category:'SAP MM', title:'Purchase Requisition source not determined', icon:'Database', priority:'P3', severity:'Medium',
    symptoms:['purchase requisition','PR source','source not determined','source of supply'],
    hypotheses:[['Missing source list',30],['Missing or invalid info record',25],['Contract/source agreement not valid',25],['Plant/purchasing data incomplete',20]],
    steps:[
      {q:'Is a valid source list maintained for the material and plant?', help:'Source determination often depends on a valid source list entry.', yes:{next:1}, no:{result:'Missing or invalid source list',cause:'No valid source of supply is maintained for the material/plant/date combination.',confidence:92,actions:['Review source list validity dates','Confirm plant and material','Maintain the approved source of supply if authorized','Run source determination again'],escalate:false}},
      {q:'Is there a valid purchasing info record or outline agreement for the vendor/material?', help:'Checks whether SAP has valid purchasing master data to select from.', yes:{next:2}, no:{result:'Purchasing master data gap',cause:'The vendor/material purchasing relationship is missing, blocked, or outside validity.',confidence:89,actions:['Check purchasing info record','Check contract/scheduling agreement validity','Verify vendor purchasing organization data','Correct master data through the approved process'],escalate:false}},
      {q:'Do purchasing organization, plant and material master purchasing views match the intended procurement setup?', help:'Organization-level inconsistencies can prevent source determination.', yes:{result:'Source determination rule or configuration issue',cause:'Valid master data exists, but source determination logic or configuration is not selecting it.',confidence:76,actions:['Compare with a working material/plant','Review quota arrangement or source determination settings','Capture PR and master-data details','Escalate configuration review to SAP MM support'],escalate:true}, no:{result:'Plant or purchasing master-data mismatch',cause:'Required organizational or material purchasing data is incomplete or inconsistent.',confidence:91,actions:['Correct plant/purchasing organization assignment','Complete required purchasing views','Verify procurement type and vendor data','Retry source determination'],escalate:false}}
    ]
  },
  {
    id:'sap-gr-posting', category:'SAP MM', title:'Goods Receipt cannot be posted', icon:'HardDrive', priority:'P2', severity:'High',
    symptoms:['goods receipt','GR posting','MIGO','movement type','cannot post GR'],
    hypotheses:[['PO quantity/status issue',30],['Movement type or stock issue',25],['Posting period closed',20],['Account determination/configuration issue',15],['Authorization issue',10]],
    steps:[
      {q:'Is the PO item still open for goods receipt and does the remaining quantity allow the posting?', help:'Checks the purchasing document before investigating configuration.', yes:{next:1}, no:{result:'PO status or quantity prevents GR',cause:'The PO item is closed, delivery-completed, deleted, or the remaining quantity does not permit the receipt.',confidence:94,actions:['Review PO item status and history','Verify ordered versus received quantity','Correct the PO only through the approved process','Retry the GR after the document is valid'],escalate:false}},
      {q:'Does SAP show a posting-period or accounting-related error?', help:'Separates logistics validation from FI integration issues.', yes:{next:2}, no:{result:'Movement type, stock, or document-data issue',cause:'The GR is blocked by movement type rules, required fields, batch/serial data, or stock-related validation.',confidence:82,actions:['Confirm movement type, plant and storage location','Review batch/serial requirements','Check error long text','Compare with a successful GR for the same process'],escalate:false}},
      {q:'Is the relevant MM/FI posting period open?', help:'A closed posting period prevents material and accounting documents from posting.', yes:{result:'MM-FI account determination or posting configuration issue',cause:'The logistics document is valid but the accounting posting cannot determine or use the required account.',confidence:86,actions:['Capture the exact account determination message','Review valuation class and transaction key with authorized support','Compare material/account settings with a working example','Escalate OBYC/configuration changes to SAP MM/FI support'],escalate:true}, no:{result:'Posting period closed',cause:'The goods movement date falls in a closed MM or FI posting period.',confidence:97,actions:['Confirm intended posting date','Use an allowed date if business policy permits','Request period opening through Finance if required','Retry after the period is available'],escalate:true}}
    ]
  },
  {
    id:'sap-miro-blocked', category:'SAP MM', title:'MIRO invoice blocked for payment', icon:'Mail', priority:'P2', severity:'High',
    symptoms:['MIRO','invoice blocked','payment block','quantity variance','price variance'],
    hypotheses:[['Quantity variance',30],['Price variance',30],['Missing/incorrect GR',20],['Tolerance configuration',10],['Manual payment block',10]],
    steps:[
      {q:'Does the invoice show a quantity variance against the PO/GR?', help:'Three-way match quantity differences are a common reason for invoice blocking.', yes:{next:1,boost:{'Quantity variance':30,'Missing/incorrect GR':15}}, no:{next:2,boost:{'Quantity variance':-15,'Price variance':15}}},
      {q:'Does PO history show the expected goods receipt quantity before the invoice?', help:'Confirms whether the invoice quantity is supported by the receipt history.', yes:{result:'Invoice quantity exceeds tolerance',cause:'The invoice quantity differs from the accepted PO/GR quantity beyond configured tolerance.',confidence:93,actions:['Compare invoice, PO and GR quantities','Confirm whether another GR is expected','Correct the invoice or GR through the approved business process','Release the block only after the variance is resolved'],escalate:false}, no:{result:'Missing or incorrect goods receipt',cause:'The invoice was posted before the expected GR or the GR quantity/document is incorrect.',confidence:95,actions:['Verify physical receipt','Post or correct the GR if authorized and supported by business evidence','Recheck PO history','Reprocess/release the invoice after the three-way match is valid'],escalate:false}},
      {q:'Does the invoice show a price variance from the PO conditions?', help:'Checks the other major three-way-match reason for blocking.', yes:{result:'Invoice price variance',cause:'The vendor invoice price differs from the PO price beyond the permitted tolerance.',confidence:94,actions:['Compare PO conditions with invoice price','Check planned delivery costs and tax treatment','Confirm whether the PO or invoice should be corrected','Release only after the commercial discrepancy is approved/resolved'],escalate:false}, no:{result:'Invoice block requires tolerance or manual-block review',cause:'No obvious quantity/price mismatch is present; the block may come from tolerance configuration, duplicate checks, or a manual payment block.',confidence:78,actions:['Review invoice block reason and payment block','Check duplicate invoice indicators','Review applicable tolerance keys with SAP support','Escalate configuration changes to MM/FI support'],escalate:true}}
    ]
  },
  {
    id:'sap-grir-balance', category:'SAP MM', title:'GR/IR balance not clearing', icon:'CloudCog', priority:'P3', severity:'Medium',
    symptoms:['GR/IR','GRIR','unmatched GR','unmatched invoice','clearing issue'],
    hypotheses:[['Quantity mismatch',30],['Price mismatch',20],['Missing invoice',20],['Missing/reversed GR',20],['Historical item requiring reconciliation',10]],
    steps:[
      {q:'Does PO history show both a goods receipt and an invoice receipt for the open item?', help:'A missing side of the GR/IR pair is the first thing to confirm.', yes:{next:1}, no:{result:'Incomplete GR/IR lifecycle',cause:'Either the goods receipt or invoice receipt is missing, reversed, or not linked as expected.',confidence:94,actions:['Review PO history','Confirm whether GR or invoice is still expected','Check reversal documents','Complete/correct the business document rather than forcing an accounting clear'],escalate:false}},
      {q:'Do the GR and invoice quantities match?', help:'Quantity differences keep GR/IR open even when both documents exist.', yes:{next:2}, no:{result:'GR/IR quantity mismatch',cause:'Received and invoiced quantities differ for the PO item.',confidence:95,actions:['Compare GR and invoice quantities','Check partial delivery/invoice expectations','Correct incorrect logistics documents through the approved process','Reconcile after quantities align'],escalate:false}},
      {q:'Do the amounts differ because of price or exchange-rate effects?', help:'Explains residual values when quantities match.', yes:{result:'GR/IR value difference',cause:'Price, planned delivery cost, or exchange-rate differences created a residual GR/IR balance.',confidence:88,actions:['Review PO pricing and invoice conditions','Check currency/exchange-rate timing','Use the organization’s approved GR/IR reconciliation process','Engage MM/FI support for material differences'],escalate:true}, no:{result:'Historical GR/IR item requires reconciliation',cause:'Documents appear matched but an older residual or account-assignment detail remains open.',confidence:75,actions:['Review detailed PO history and accounting documents','Check reversals and prior-period postings','Use approved GR/IR reconciliation reporting','Escalate unexplained residuals to MM/FI support'],escalate:true}}
    ]
  },
  {
    id:'sap-vendor-blocked', category:'SAP MM', title:'Vendor / Business Partner blocked for purchasing', icon:'KeyRound', priority:'P3', severity:'Medium',
    symptoms:['vendor blocked','business partner blocked','supplier blocked','purchasing block'],
    hypotheses:[['Purchasing block',40],['Company-code block',20],['Incomplete purchasing data',20],['Authorization/workflow issue',20]],
    steps:[
      {q:'Is the supplier explicitly blocked at purchasing organization or central level?', help:'Checks the most direct reason a vendor cannot be used in purchasing.', yes:{result:'Supplier purchasing block',cause:'The vendor/business partner is blocked for purchasing at the relevant organizational level.',confidence:97,actions:['Confirm why the block exists','Do not bypass compliance or master-data controls','Request unblock through the approved vendor-master process','Retest only after authorized approval'],escalate:true}, no:{next:1}},
      {q:'Is required purchasing organization data complete for the supplier?', help:'Missing purchasing data can look like a block during document creation.', yes:{result:'Supplier usage issue outside basic purchasing master data',cause:'The supplier is available, but partner functions, source data, workflow, or document-specific rules prevent use.',confidence:77,actions:['Check partner functions and source data','Review document error text','Compare with a working supplier','Escalate persistent issues to vendor-master/SAP MM support'],escalate:true}, no:{result:'Incomplete supplier purchasing master data',cause:'Required purchasing organization data or partner information is missing.',confidence:92,actions:['Complete approved purchasing data','Verify order currency, terms and partner functions','Save master data through the approved workflow','Retry purchasing document creation'],escalate:false}}
    ]
  },
  {
    id:'sap-material-master', category:'SAP MM', title:'Material master data prevents purchasing or posting', icon:'Database', priority:'P3', severity:'Medium',
    symptoms:['material master','missing view','valuation class','unit of measure','material error'],
    hypotheses:[['Missing plant/purchasing view',30],['Valuation/accounting data missing',25],['UOM or conversion issue',20],['Material status/block',15],['Organizational extension missing',10]],
    steps:[
      {q:'Is the material extended to the required plant and purchasing organization context?', help:'A material must contain the required organizational views before it can be used.', yes:{next:1}, no:{result:'Material not extended to required organizational level',cause:'The required plant/purchasing/storage views are missing for the business process.',confidence:96,actions:['Confirm intended plant and organizational levels','Extend the material through the approved master-data process','Maintain required purchasing/storage fields','Retry the transaction'],escalate:false}},
      {q:'Does the error mention valuation class, accounting data, or account determination?', help:'Identifies MM-FI master-data dependencies.', yes:{result:'Material valuation/accounting master-data issue',cause:'Valuation class or accounting data is missing/inconsistent for the plant/valuation area.',confidence:93,actions:['Review accounting/valuation views','Compare valuation class with a similar material','Do not change account determination without approval','Escalate configuration questions to MM/FI support'],escalate:true}, no:{next:2}},
      {q:'Does the issue involve order unit, base unit, or unit conversion?', help:'UOM inconsistencies can block PO, GR and inventory postings.', yes:{result:'Material unit-of-measure issue',cause:'The requested purchasing or posting unit is missing or has an invalid conversion.',confidence:92,actions:['Review base and alternative units','Validate conversion factors','Correct master data through approved governance','Retest the purchasing/posting transaction'],escalate:false}, no:{result:'Material status or process-specific master-data issue',cause:'A material status, procurement setting, or required field is preventing the transaction.',confidence:78,actions:['Check material status and purchasing settings','Review the exact application error','Compare with a working material','Escalate unresolved master-data rules to SAP MM support'],escalate:true}}
    ]
  },
  {
    id:'sap-account-determination', category:'SAP MM', title:'Automatic account determination error', icon:'CloudCog', priority:'P2', severity:'High',
    symptoms:['account determination','OBYC','G/L account','account not determined','FI posting error'],
    hypotheses:[['Missing OBYC mapping',35],['Valuation class mismatch',30],['Transaction key/account modifier issue',20],['G/L account master/configuration issue',15]],
    steps:[
      {q:'Does the error identify a transaction key, valuation class, or missing G/L account?', help:'These values point directly to the MM-FI account determination path.', yes:{next:1}, no:{result:'Accounting integration error requires document analysis',cause:'The posting failed in MM-FI integration but the message does not provide enough account-determination detail.',confidence:72,actions:['Capture the complete error and long text','Record material, plant, movement type and document type','Compare with a successful posting','Escalate to MM/FI support for controlled analysis'],escalate:true}},
      {q:'Does the material use the expected valuation class for this posting?', help:'An unexpected valuation class can route the posting to an unmapped account.', yes:{result:'Account determination configuration gap',cause:'The expected valuation class is present, but the transaction key/account modifier does not have a valid G/L mapping.',confidence:91,actions:['Capture transaction key, valuation class and account modifier','Compare with the approved account-determination design','Do not change OBYC directly in production','Escalate configuration correction to authorized MM/FI support'],escalate:true}, no:{result:'Material valuation class mismatch',cause:'The material master valuation class does not match the intended account determination setup.',confidence:93,actions:['Verify material type and allowed valuation classes','Confirm the correct accounting treatment with Finance','Correct master data only through approved governance','Retest the posting'],escalate:true}}
    ]
  },
  {
    id:'sap-authorization', category:'SAP MM', title:'SAP transaction or function access denied', icon:'Shield', priority:'P3', severity:'Medium',
    symptoms:['SAP authorization','not authorized','authorization error','SU53','access denied'],
    hypotheses:[['Missing role authorization',50],['Organizational restriction',25],['Expired/inactive role',15],['Wrong transaction/app',10]],
    steps:[
      {q:'Does SAP show a clear authorization error after the failed action?', help:'Confirms this is an access-control issue rather than a business validation.', yes:{next:1}, no:{result:'Business validation or application error, not confirmed authorization failure',cause:'The action failed without a clear authorization denial.',confidence:70,actions:['Read the full application error','Verify document/master data first','Reproduce the exact failed action','Escalate only if an authorization object is identified'],escalate:false}},
      {q:'Can the approved authorization check (for example SU53 or your organization’s access process) identify a missing authorization?', help:'Uses the organization’s standard evidence rather than guessing roles.', yes:{result:'Missing SAP authorization',cause:'The user role lacks the required authorization object/value for the action or organizational level.',confidence:96,actions:['Capture the failed authorization evidence','Request least-privilege access through the approved process','Do not copy broad roles from another user','Retest after role provisioning and user-buffer refresh'],escalate:true}, no:{result:'Authorization issue requires security-role analysis',cause:'The denial is reproducible but the missing object/value is not obvious from the user-level check.',confidence:82,actions:['Record transaction/app and exact action','Capture timestamp and error details','Engage SAP Security/GRC for trace analysis','Retest after approved role correction'],escalate:true}}
    ]
  },
  {
    id:'sap-ariba-integration', category:'SAP MM', title:'SAP Ariba procurement document not reaching ERP', icon:'CloudOff', priority:'P2', severity:'High',
    symptoms:['Ariba','CIG','procurement integration','document not reaching SAP','integration failure'],
    hypotheses:[['Integration message failed',35],['Master-data mapping issue',25],['Authentication/endpoint issue',20],['Document validation/configuration issue',20]],
    steps:[
      {q:'Is there a failed or errored integration message for the document?', help:'Establishes whether the document left Ariba and reached the integration layer.', yes:{next:1}, no:{result:'Document did not enter the expected integration flow',cause:'The document may still be pending workflow, export, event generation, or upstream validation.',confidence:83,actions:['Confirm source-document approval/status','Check whether export/integration was triggered','Verify the intended integration route','Escalate persistent source-side failures to Ariba support'],escalate:true}},
      {q:'Does the message error reference vendor, material, plant, purchasing organization, or other mapped master data?', help:'Master-data mismatches are common cross-system integration failures.', yes:{result:'Ariba-to-SAP master-data mapping issue',cause:'A source value cannot be mapped to a valid ERP organizational or master-data value.',confidence:92,actions:['Capture the failed payload/message ID','Verify supplier/material/org mappings','Correct mapping/master data through the approved process','Reprocess the message after correction'],escalate:true}, no:{next:2}},
      {q:'Does the error indicate connectivity, certificate, authentication, or endpoint failure?', help:'Separates technical connectivity from business-document validation.', yes:{result:'Ariba integration connectivity/authentication issue',cause:'The integration channel, certificate, credentials, or endpoint is unavailable or invalid.',confidence:91,actions:['Check integration endpoint/service health','Review certificate/credential validity with authorized support','Confirm network connectivity','Escalate to integration/platform support'],escalate:true}, no:{result:'Ariba-to-ERP document validation/configuration issue',cause:'The message reached integration processing but failed business validation or ERP configuration.',confidence:82,actions:['Review the exact application error','Compare payload fields with a successful document','Validate document type and organizational configuration','Escalate unresolved rules to Ariba/SAP functional support'],escalate:true}}
    ]
  }
];
