// A confirmed diagnostic answer narrows a cause; a captured error alone does not.
const unresolved = (team, actions) => ({result:'Root cause not confirmed',cause:'The available evidence does not confirm a specific root cause.',confidence:0,actions:[...actions,`Escalate to ${team} with the exact message, document context and checks performed`],escalate:true,assignment:team});
const confirmed = (cause, actions, team) => ({result:cause,cause,confidence:90,actions,escalate:Boolean(team),...(team?{assignment:team}:{})});
const flow = (id,category,title,symptoms,checks,team,context) => ({
 id,category,title,symptoms,icon:'Database',priority:'P2',severity:'High',
 hypotheses:[...checks.map(c=>[c.cause,Math.floor(100/(checks.length+1))]),['Cause not yet confirmed',Math.floor(100/(checks.length+1))]],
 steps:checks.map((c,i)=>({q:c.q,help:c.help||'Confirm this from the exact SAP message and the relevant document or master-data record; do not guess.',yes:confirmed(c.cause,c.actions,c.team),no:i<checks.length-1?{next:i+1}:unresolved(team,context)}))
});
export const sapFunctionalScenarios=[
 flow('sap-invoice-posting','SAP MM','Invoice posting validation failure',['invoice duplicate','wrong PO','invoice currency','invoice tax'],[
  {q:'Does the duplicate-invoice check identify an existing invoice for the same supplier, reference and company code?',cause:'Existing invoice triggers duplicate-invoice prevention',actions:['Compare the existing invoice with the supplier reference and amount','Do not post a duplicate or bypass the duplicate check','Ask Accounts Payable to confirm whether a correction is required'],team:'SAP MM/FI Accounts Payable'},
  {q:'Does the invoice reference a different PO, supplier or currency from the approved supporting documents?',cause:'Invoice reference or currency does not match the approved document',actions:['Compare invoice, PO, supplier and currency','Confirm the correct reference with Accounts Payable','Correct the document through the approved invoice process','Retest invoice validation'],team:'SAP MM/FI Accounts Payable'},
  {q:'Does the error identify an invalid tax code for the invoice company code or posting date?',cause:'Invoice tax code is invalid for the posting context',actions:['Capture tax code, company code and posting date','Ask Finance to validate the permitted tax treatment','Retest after approved correction'],team:'SAP FI'}
 ],'SAP MM/FI',['Capture invoice reference, PO, supplier, company code and exact message']),
 flow('sap-posting-period','SAP FI','SAP posting period blocks transaction',['posting period closed','closed posting period','MM period','FI period'],[
  {q:'Does the error and posting-date check confirm that the required MM or FI period is closed for this company code?',cause:'Required posting period is closed',actions:['Capture posting date, company code and period error','Check applicable MM and FI periods with authorized support','Use an allowed date only if business policy permits; otherwise request Finance period handling','Retest the original posting after authorized correction'],team:'SAP MM/FI'}
 ],'SAP MM/FI',['Record transaction, company code, posting date and message class/number']),
 flow('sap-uom','SAP MM','Material unit-of-measure conversion issue',['alternative UOM','base unit of measure','unit conversion'],[
  {q:'Does the material master show a missing or incorrect conversion between the requested unit and the base unit?',cause:'Material unit conversion is missing or incorrect',actions:['Record material and base/alternative units','Validate numerator and denominator against approved material data','Request master-data correction through governance','Retest with the validated unit conversion'],team:'SAP MM Master Data'}
 ],'SAP MM Master Data',['Capture the unit error and material/plant context']),
 flow('sap-account-assignment','SAP PS','WBS, project or cost-object account assignment failure',['WBS','account assignment','network activity','project stock','settlement rule'],[
  {q:'Does the referenced WBS, cost center or internal order show a posting lock, technical completion, closure or expired validity for the posting date?',cause:'Account-assignment object status or validity blocks posting',actions:['Record object ID, status and posting date','Confirm the business reason for the restriction','Request authorized PS/CO owner review; do not bypass locks or reopen objects without approval','Retest after approved status or validity handling'],team:'SAP PS/CO'},
  {q:'Does the error confirm budget availability control has rejected the posting?',cause:'Project or order budget availability control blocks posting',actions:['Capture budget control message and object','Review assigned budget and commitments with the project controller','Request approved budget handling; do not bypass availability control'],team:'SAP PS/CO'},
  {q:'Does the document or object show an incorrect account-assignment category, company code, controlling area, WBS or network activity?',cause:'Account-assignment category or organizational object mismatch',actions:['Compare document assignment with the intended business process','Validate company code, controlling area and object ownership','Correct document or master data only through the approved process','Retest the posting'],team:'SAP MM/PS/CO'},
  {q:'Does the settlement error identify a missing or invalid settlement rule for the project or order?',cause:'Settlement rule is missing or invalid',actions:['Capture settlement message and object','Request authorized PS/CO settlement-rule review','Retest the settlement after approved correction'],team:'SAP PS/CO'}
 ],'SAP PS/CO',['Capture document, object, message and posting date']),
 flow('sap-goods-movement','SAP MM','Goods movement, transfer or return cannot be posted',['movement 122','movement 123','movement 161','movement 162','movement 343','movement 344','movement 321','movement 322','movement 311','movement 301','movement 309'],[
  {q:'Does the error confirm insufficient stock or a mismatch in plant, storage location, batch, serial number, special stock or stock type for this movement?',cause:'Required goods-movement stock context is unavailable or inconsistent',actions:['Record movement type and source/target stock context','Check stock and document history; include quality or warehouse restrictions','Correct the business stock flow only if authorized and operationally valid','Retest the requested movement'],team:'SAP MM/WM'},
  {q:'Does SAP identify an invalid reference document, return quantity, movement type or required field for the intended return or transfer?',cause:'Goods-movement reference or movement data is invalid',actions:['Confirm original document and fiscal year where required','Validate approved movement/process and permitted quantity','Review error long text and correct supported document fields','Retest; use the approved reversal flow for cancellation'],team:'SAP MM'}
 ],'SAP MM',['Capture exact error, movement type and stock/document context']),
 flow('sap-idoc-data','SAP Basis','IDoc processing failure',['IDoc','status 51','master-data mismatch'],[
  {q:'Does the IDoc status long text identify a source value that is missing or mapped to invalid ERP master data?',cause:'IDoc master-data mapping or validation failure',actions:['Capture IDoc number, status, segment field and error text','Validate the failing material, supplier or organizational mapping','Correct master data through the approved owner','Reprocess through the approved procedure and verify no duplicate business document'],team:'SAP Integration/MM'},
  {q:'Does the technical log identify an RFC, certificate, endpoint or authentication failure?',cause:'IDoc technical communication failure',actions:['Capture destination and technical log','Request authorized Basis/integration connectivity review','Retry approved processing after correction'],team:'SAP Basis/Integration'}
 ],'SAP Basis/Integration',['Capture IDoc number, status history and application error'])
];
