name: Secret scan
on:
  workflow_call:
permissions:
  contents: read
  pull-requests: read
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITLEAKS_ENABLE_COMMENTS: 'false'
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: 'false'
      - name: Scan complete repository history
        run: gitleaks detect --redact --log-opts="--all" --exit-code=1
